/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:205183:
  if (model=="girl")
    model = "man";
    
  else
    model = "girl";
} //_CODE_:button1:205183:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:802446:
} //_CODE_:textfield1:802446:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:422077:
  currentTopIndex = 2;
  currentPantsIndex = 3;
  currentAccessoryIndex = 0;
} //_CODE_:button2:422077:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:232175:
  currentTopIndex = 4;
  currentPantsIndex = 2;
  currentAccessoryIndex = 2;
} //_CODE_:button3:232175:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:784459:
  currentTopIndex = 3;
  currentPantsIndex = 5;
  currentAccessoryIndex = 4;
} //_CODE_:button4:784459:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:910962:
  currentTopIndex = 4;
  currentPantsIndex = 0;
  currentAccessoryIndex = 3;
} //_CODE_:button5:910962:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:607897:
  currentTopIndex = 6;
  currentPantsIndex = 0;
  currentAccessoryIndex = 0;
} //_CODE_:button6:607897:

public void button7_click1(GButton source, GEvent event) { //_CODE_:button7:678619:
  currentTopIndex = 7;
  currentPantsIndex = 4;
  currentAccessoryIndex = 2;
} //_CODE_:button7:678619:

public void button8_click1(GButton source, GEvent event) { //_CODE_:button8:509197:
  userWord = textfield1.getText();
  wordFound = false;
  for (String line : allData) {
    String[] parts = splitTokens(line, ",");

    // Check if parts array is not empty and has at least 4 elements
    if (parts.length >= 4) {
      for (int i = 0; i < parts.length; i++) {
        String currentWord = parts[i].trim();

        if (currentWord.equals(userWord)) {
          // Word found, get the corresponding numbers
          currentTopIndex = int(parts[parts.length - 3]);
          currentPantsIndex = int(parts[parts.length - 2]);
          currentAccessoryIndex = int(parts[parts.length - 1]);
          
          println("Now displaying outfit for your query:", userWord+"!");
            
          wordFound = true;
          break;
        }
      }
    }
  }

  if (!wordFound) {
    // Handle case where the word is not found
    println("Word is not in the list!");
  }
} //_CODE_:button8:509197:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 30, 635, 139, 35);
  button1.setText("Change Model");
  button1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  textfield1 = new GTextField(this, 55, 61, 200, 47, G4P.SCROLLBARS_NONE);
  textfield1.setPromptText("Search");
  textfield1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  button2 = new GButton(this, 54, 180, 60, 35);
  button2.setText("Fit 1");
  button2.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 54, 236, 60, 35);
  button3.setText("Fit 2");
  button3.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 54, 290, 60, 35);
  button4.setText("Fit 3");
  button4.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 137, 180, 60, 35);
  button5.setText("Fit 4");
  button5.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(this, 138, 236, 60, 35);
  button6.setText("Fit 5");
  button6.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  button6.addEventHandler(this, "button6_click1");
  button7 = new GButton(this, 137, 290, 60, 35);
  button7.setText("Fit 6");
  button7.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button7.addEventHandler(this, "button7_click1");
  button8 = new GButton(this, 273, 68, 40, 32);
  button8.setText("done");
  button8.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  button8.addEventHandler(this, "button8_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextField textfield1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GButton button6; 
GButton button7; 
GButton button8; 
